### ISSUE TITLE
Broken on master of Mathics?

### ISSUE THREAD

**Issue by sdwfrost** [mathics/IMathics#13]
I'd love to get the Jupyter kernel working with the latest Mathics; I see there's an outstanding pull request (that also doesn't fix). The error I get at present is

```sh
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/imathics-0.1-py3.5.egg/imathics/__main__.py", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/imathics-0.1-py3.5.egg/imathics/kernel.py", line 10, in <module>
ImportError: cannot import name 'parse_lines'
```

**Comment by GokulNC** [comment]
This is the latest error:

```
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python37-32\Scripts\jupyter-console.EXE\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-118>", line 2, in initialize
  File "c:\program files (x86)\python37-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_console\app.py", line 142, in initialize
    self.init_shell()
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_console\app.py", line 109, in init_shell
    JupyterConsoleApp.initialize(self)
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_client\consoleapp.py", line 341, in initialize
    self.init_kernel_manager()
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_client\consoleapp.py", line 293, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_client\manager.py", line 254, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_client\manager.py", line 178, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_client\manager.py", line 84, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "c:\program files (x86)\python37-32\lib\site-packages\jupyter_client\kernelspec.py", line 235, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named mathics
```
